# Generated by Django 4.1.4 on 2022-12-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('Горячие блюда', 'Hot Meals'), ('Напитки', 'Drink'), ('Десерты', 'Dessert'), ('NO_TYPE', 'No Type')], default='NO_TYPE', max_length=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название блюда'),
        ),
    ]
