# Generated by Django 4.1.4 on 2022-12-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0002_alter_meal_description_alter_meal_meal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealclick',
            name='session',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
