# Generated by Django 4.1.4 on 2022-12-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0005_mealclick_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealclick',
            name='session',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Имя сессии'),
        ),
    ]
