# Generated by Django 4.1.4 on 2022-12-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0006_alter_mealclick_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealclick',
            name='user',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Пользователь'),
        ),
    ]
