# Generated by Django 4.1.4 on 2023-01-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0007_alter_mealclick_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meal_images/%Y/%m/%d/%H/%M/%S/')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cafe_core_app.meal')),
            ],
        ),
    ]
