# Generated by Django 4.1.4 on 2023-01-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0008_mealimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealimage',
            name='image',
            field=models.ImageField(upload_to='meal_images/%Y/%m/%d/'),
        ),
    ]
